# Minimal KiBot config (tilpass senere)
kibot:
  version: 1

outputs:
  - name: gerbers
    type: gerber
    dir: fabrication/gerbers
  - name: drill
    type: excellon
    dir: fabrication/drill
  - name: bom_csv
    type: bom
    options: { format: CSV, ref_sep: ", " }
    dir: fabrication/bom
  - name: pos_csv
    type: position
    options: { format: CSV }
    dir: fabrication/pos
  - name: pdf_sch
    type: pdf_sch_print
    dir: docs/pdf
  - name: pdf_pcb
    type: pdf_pcb_print
    dir: docs/pdf
