kibot:
  version: 1

global:
  output: checks

preflight:
  check_zone_fills: true
  erc: true
  drc: true

  filters:

  set_text_variables:
    - name: 'git_hash'
      command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
      before: 'Git:'

    - name: 'date'
      command: 'date --iso-8601=minutes'

outputs:
  - name: 'bom_xlsx'
    comment: "Spreadsheet for the Bill of Materials"
    type: bom
    dir: fabrication/bom
    options: &bom_options
      xlsx:
        datasheet_as_link: MFP
        title: 'KiBot variants example'
        max_col_width: 40
        highlight_empty: false
      columns:
        - Row
        - References
        - Quantity Per PCB
        - field: Value
          join: ['voltage', 'current', 'power', 'tolerance']
        - field: MFN
          name: Manufacturer
        - field: MFP
          name: Manf. Part
        - Footprint
      normalize_values: true

  - name: 'bom_html'
    comment: "HTML for the Bill of Materials"
    type: bom
    dir: fabrication/bom
    options:
      <<: *bom_options
      format: HTML
      html:
        datasheet_as_link: MFP
        title: 'KiBot variants example'
        highlight_empty: false

  - name: ibom
    comment: 'Prototype mounting guide'
    type: ibom
    dir: fabrication/bom
    options:
      layer_view: F

  - name: gerbers
    comment: Gerbers
    type: gerber
    dir: fabrication/gerbers
    layers:
      - copper
      - Edge.Cuts
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - F.Adhes
      - F.Fab
      - F.CrtYd
      - Dwgs.User

  - name: drill
    comment: Drill files
    type: excellon
    dir: fabrication/drill
    options:
      map:
        type: pdf
      pth_and_npth_single_file: false

  - name: position
    comment: Pick & Place
    type: position
    dir: fabrication/pos
    options:
      separate_files_for_front_and_back: false


  - name: 'print_sch'
    comment: "Schematic PDF"
    type: pdf_sch_print
    dir: docs/pdf
    options:
      # Append the variant to the title
      title: "+ (%V variant)"

  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: docs/pdf
    options:
      force_edge_cuts: true
      keep_temporal_files: true
      # Append the variant to the title
      title: "+ (%V variant)"
      # This is the worksheet we selected in the project, no need to specify it again
      # sheet_reference_layout: pcb_print.kicad_wks
      scaling: 2.0
      pages:
        - layers: [ F.Paste, F.Adhes, Dwgs.User, F.Fab ]
          sheet: 'Fabrication layers'
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.SilkS
            - layer: Dwgs.User
          sheet: 'Top layer'
        - layers: [ GND.Cu, Dwgs.User ]
          sheet: 'GND plane'
        - layers: [ Power.Cu, Dwgs.User ]
          sheet: 'Power plane'
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: B.SilkS
            - layer: Dwgs.User
          sheet: 'Bottom layer'
          mirror: true

  - name: 3D
    comment: "STEP 3D model"
    type: step
    dir: docs/3d

  - name: 3D_top_view
    comment: "3D render from top"
    type: render_3d
    dir: docs/3d
    options:
      zoom: 4
      rotate_x: 3
      rotate_z: 3
      ray_tracing: true

  - name: 3D_top_view_HQ
    comment: "3D render from top (High Quality)"
    type: blender_export
    dir: docs/3d
    options:
      render_options:
        transparent_background: true
        samples: 20
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      outputs:
        - type: blender
        - type: render    
